version: "3"

services:
  server:
    container_name: api
    build: server/.
    restart: always
    ports:
      - "3000:8080"
    volumes:
      - ./server/:/usr/src/app
    links:
      - db
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345678
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: pertani
    ports:
      - "3306:3306"
